### ISSUE TITLE
Couldn't Generate Key 

### ISSUE THREAD

**Issue by minedun6** [bisq-network/bisq#368]

**Comment by ManfredKarrer** [comment]
Did you build from source? If so you need to follow exactly the build instructions at: https://github.com/bitsquare/bitsquare/blob/master/doc/build.md#7-enable-unlimited-strength-for-cryptographic-keys

**Comment by ManfredKarrer** [comment]
Fixed in v0.4.1.

**Comment by konard** [comment]
Getting "Couldn't generate key" on Windows 10. (v0.4.2 Beta)

**Comment by ManfredKarrer** [comment]
Do you have the correct binary installed? I got that report form another user who had the 32bit binary installed on a 64 bit computer.

**Comment by konard** [comment]
I have installed 64 bit on 64 bit computer. (Bitsquare-64bit-0.4.2.exe)

Here is what I found in the log file:

```
апр-21 23:44:53.331 [Thread-26] ERROR i.b.c.c.Encryption: JCE cannot authenticate the provider BC 
апр-21 23:44:53.332 [Thread-26] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread Thread-26 
апр-21 23:44:53.332 [Thread-26] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Couldn't generate key 
```

But it strange, everything looks ok (app is working).

**Comment by ManfredKarrer** [comment]
Strange... can you send me the log files(s)?
You did not compile by yourself, right? Can you try if you can take an offer (no need to really take it just click on take offer. There it will probably fail in your case.

**Comment by ManfredKarrer** [comment]
The error is fixed now in 0.4.3. Please update if you had that issue.
https://github.com/bitsquare/bitsquare/releases/tag/v0.4.3

**Comment by konard** [comment]
[bitsquare.txt](https://github.com/bitsquare/bitsquare/files/233135/bitsquare.txt) log for 0.4.2 if you still need it.

**Comment by ManfredKarrer** [comment]
thanks but i found the issue and its fixed.

**Comment by konard** [comment]
I have installed `Bitsquare-64bit-0.4.3.exe`. Issue persists. I still get `Couldn't generate key` message on startup. May be this issue (https://github.com/bitsquare/bitsquare/issues/402) somehow related to it. Log file after first startup and shutdown: [bitsquare.txt](https://github.com/bitsquare/bitsquare/files/234949/bitsquare.txt)

**Comment by ManfredKarrer** [comment]
If u run from the jar it takes the OS jvm which miss the adjustments described in the build file  (https://github.com/bitsquare/bitsquare/blob/master/doc/build.md) .
