### ISSUE TITLE
Account signing issue with Interac e-Transfer

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#3931]
### Description

I have a completed trade where I purchased 0.01 BTC with Interac e-Transfer and the seller has an account age of 86 days and "Signed by peer and can sign peer accounts (limits lifted). The trade started Jan 26 and completed Jan 27. The Interac e-Transfer account under Account > National Currency Accounts still shows "Not signed yet".

Two others have also reported this on the forums: https://bisq.community/t/my-account-didnt-get-signed/8837

#### Version

v1.2.5

### Steps to reproduce

Only tried once with a real trade.

### Expected behaviour

Account should be signed once the trade completes. 

### Actual behaviour

Account remains unsigned after one week.

#### Device or machine

Ubuntu 18

**Comment by sqrrm** [comment]
There are a few cases like this and I haven't been able to figure why it's failing yet. I'm looking into it.

**Comment by huey735** [comment]
Another case - https://bisq.community/t/account-not-getting-signed/9053/4

**Comment by Bayernatoor** [comment]
I've been seeing alot of reports of this happening so i tested it out myself. 

I completed a CAD/BTC trade yesterday using the e-transfer payment method. The seller's account has been signed for 143 days and could sign peers (limits lifted). My account was not signed prior to the trade and had been created 79 days ago. 

Upon completion of the trade my account was not signed - If i look under Account Signing Status it comes up as not signed. 

This also happened a long time ago to another one of my addresses.

**Comment by Bayernatoor** [comment]
I went looking through my logs for any clues as to what may be causing this. The fields indicating signing are showing  as False. 

![image](https://user-images.githubusercontent.com/55212954/78504880-5a4a1d00-7735-11ea-8900-ea1254e8a615.png)





Perhaps, the peer is unable to sign even though their account shows them as being capable of it.

**Comment by sqrrm** [comment]
This is a known issue with one of the signedwitnesses in the CAD market. I don't have a good solution yet. So far I can only think of invalidating all CAD witnesses that depend on that account, but that might invalidate the whole CAD market which would be quite intrusive.

**Comment by Bayernatoor** [comment]
@sqrrm i see...is there anything i can do on my end to test?

**Comment by sqrrm** [comment]
At this point there is nothing to do, unless you happen to have an original `SignedWitnessStore` file from October last year. I doubt anyone has it though.

**Comment by Bayernatoor** [comment]
Darn, all i've got is an `AccountAgeWitnessStore` from march 2019. I'll keep looking, may have another backup lying around somewhere.

**Comment by Bayernatoor** [comment]
@sqrrm Oh, I found a `SignedWitnessStore` dated october 31st 2019.

**Comment by sqrrm** [comment]
@Bayernatoor could you send it to sqrrm1@gmail.com? I'll take a look if it has the missing data.

**Comment by sqrrm** [comment]
It's a common data store so there is nothing private in there.

**Comment by Bayernatoor** [comment]
@sqrrm  Yep, sending.

**Comment by ericrpatton** [comment]
Does anyone need a guinea pig to help test out anything? I'm experiencing this bug as well. I'd to help if possible.

**Comment by TeaPe** [comment]
Hey, I've also been having this issue. Both with existing CAD e-Transfer accounts becoming no longer signed, and trying to get a new account signed. I was unable to accomplish either. I [posted about it on Reddit](https://www.reddit.com/r/bisq/comments/gheyl4/signed_account_no_longer_signed/) a few weeks back. Just hoping for a solution.  I have been using Bisq for years and have made many backups. I might be able to send over a `SignedWitnessStore` that's older than October of last year if you would like another one to compare. Let me know and I can go and check for you.

**Comment by ptica** [comment]
Hi, a Revolut signed account has not signed my Revolut account though

> Signed by peer and can sign peer accounts (limits lifted)

what info is needed to properly debug the issue?

**Comment by PepeLapiu** [comment]
I gotta say this is a big problem with Bisq right now in Canada. Interact e-transfers are by far the most popular way of trading Bitcoin. 
I am a trader and I joined Bisq to expand my reach and because I love anything open source, anonymous, and p2p. But right now Bisq is pretty much worthless to me.
I'll hang around and see if this problem gets fixed. 
I'm not a hacker so I have no idea how I can help. But if you know of a way I can help, let me know.

**Comment by Bayernatoor** [comment]
@PepeLapiu @TeaPe  @ericrpatton Just an FYI in case you hadn't seen it yet but this issue has been fixed, Interac etransfer accounts are now being signed and I have yet to run into a situation where I failed to sign another peer. 

Might be time to give it another try :) DM me if you need signing and I can place an order.

@sqrrm I am also assume that since this is fixed the issue can be closed.

**Comment by TeaPe** [comment]
@Bayernatoor can confirm. I noticed one day that my account changed back to "signed" and it even kept up with the number of days signed. It must of changed back sometime in August. Thanks for letting everybody know.

**Comment by Bayernatoor** [comment]
> @Bayernatoor can confirm. I noticed one day that my account changed back to "signed" and it even kept up with the number of days signed. It must of changed back sometime in August. Thanks for letting everybody know.

That's great to hear!

**Comment by bisqta** [comment]
I am having the same issue. Traded with someone yesterday who had an Interac signed account with 355 days age. Transaction is complete but my account is still not signed. Maybe because I was the maker and not the taker? I thought it would work both ways?

**Comment by ripcurlx** [comment]
> I am having the same issue. Traded with someone yesterday who had an Interac signed account with 355 days age. Transaction is complete but my account is still not signed. Maybe because I was the maker and not the taker? I thought it would work both ways?

It is not so much about taker or maker role, but rather seller or buyer. Only seller can sign other accounts. More details can be found here: https://bisq.wiki/Account_limits#How_to_get_an_account_signed

**Comment by dsd373** [comment]
Any idea when this is going to get fixed? I have been using Bisq for several months BTC-CAD and BTC-GBP I have completed a number of trades and my account is still not signed. I am not sure if all my trading partners have been able to sign transactions but some definitely have like my transaction today with someone who has an account that has been signed for 37 days. My very first transaction several months ago was with someone who's account at the time had been signed for over 300 days.

**Comment by dsd373** [comment]
I have just purchased 0.001 BTC by e-transfer from an account which has been signed for 103 days and is able to sign peer accounts. My account still in not signed. How do I get my account signed?

**Comment by ripcurlx** [comment]
> I have just purchased 0.001 BTC by e-transfer from an account which has been signed for 103 days and is able to sign peer accounts. My account still in not signed. How do I get my account signed?

If you are the BTC buyer and the seller was able to sign other accounts you should have been signed. Could you please have a look at your log file around the completion of your trade if there was an error?

**Comment by dsd373** [comment]
> > I have just purchased 0.001 BTC by e-transfer from an account which has been signed for 103 days and is able to sign peer accounts. My account still in not signed. How do I get my account signed?
> 
> If you are the BTC buyer and the seller was able to sign other accounts you should have been signed. Could you please have a look at your log file around the completion of your trade if there was an error?

I assume that is the file bisq.log - the earliest entry in the log file is less than 24 hours old and about 6 hours after the trade.

**Comment by dsd373** [comment]
> > I have just purchased 0.001 BTC by e-transfer from an account which has been signed for 103 days and is able to sign peer accounts. My account still in not signed. How do I get my account signed?
> 
> If you are the BTC buyer and the seller was able to sign other accounts you should have been signed. Could you please have a look at your log file around the completion of your trade if there was an error?

I see now that the log files get sequentially numbered and a new one started as they hit a size limit. I have checked the log file around the time of the transaction, and while I will be the first to admit that I do not fully understand everything that is being written I understand the gist of it and cannot see anything that looks like it is an error.

**Comment by MwithM** [comment]
> I have just purchased 0.001 BTC by e-transfer from an account which has been signed for 103 days and is able to sign peer accounts. My account still in not signed. How do I get my account signed?

You should have bought at least 0.0025BTC. https://bisq.wiki/Account_limits#Buying_BTC

**Comment by dsd373** [comment]
> > I have just purchased 0.001 BTC by e-transfer from an account which has been signed for 103 days and is able to sign peer accounts. My account still in not signed. How do I get my account signed?
> 
> You should have bought at least 0.0025BTC. https://bisq.wiki/Account_limits#Buying_BTC

Thank you I totally missed that part on that page. 

Unfortunately my problem persists. Yesterday I purchased 0.01BTC from someone that has had a signed account for over 100 days and is able to sign peer accounts. the transaction has completed and my account still is not signed.

**Comment by MwithM** [comment]
Sorry to hear that. Try creating the account again, with a different salt, and buying another time.
