### ISSUE TITLE
Bank name on offer id is = (null)

### ISSUE THREAD

**Issue by bitcoinuser** [bisq-network/bisq#550]
See the screenshot.
![captura de tela de 2016-07-27 10-26-48](https://cloud.githubusercontent.com/assets/1178856/17176828/eaf921f2-53e4-11e6-8e8e-d1790a72525b.png)

**Comment by ManfredKarrer** [comment]
Should be fixed in new version which just was released. If not please re-open.

**Comment by bitcoinuser** [comment]
Was reproduced in the last version: 0.4.9.1.

**Comment by bitcoinuser** [comment]
Could you please re-open?

**Comment by bitcoinuser** [comment]
Today I saw an offer that appear the bank name correctly. But I still see null message on others.

![captura de tela de 2016-07-28 11-02-50](https://cloud.githubusercontent.com/assets/1178856/17215448/44ccf342-54b3-11e6-8781-e50c33967f99.png)

**Comment by ManfredKarrer** [comment]
The null comes probably from offers created with the old clients. The field is set to the bank name in the new version but to the bank ID (null) in the old version inside the offer... I will add a check to not display anything in that case, but should disappear once there are no old offers out anymore.

**Comment by bitcoinuser** [comment]
Understood.

Thanks.

**Comment by ManfredKarrer** [comment]
Added the change already for the next version...

**Comment by ManfredKarrer** [comment]
@bitcoinuser Btw. I appreciate a lot your input and hel with testing and bug reports! 
Would you be interested to be one of the pre-release testers? I send to a few people new versions before they are officially released for testing. Requirement is that they are responsive so in case there are critical bugs in those versions that they can update quickly to a fixed version. Drop me an email if u are interested.

**Comment by bitcoinuser** [comment]
I accept. I will send you an email.

Thanks

**Comment by bitcoinuser** [comment]
What is your email?

**Comment by ManfredKarrer** [comment]
Cool! manfred[at]bitsquare[dot]io
