### ISSUE TITLE
Failed trade; unable to open support; Cannot invoke "org.bitcoinj.core.Transaction.getLockTime()" because the return value of "bisq.core.trade.Trade.getDelayedPayoutTx()" is null

### ISSUE THREAD

**Issue by ryenski** [bisq-network/bisq#5796]
### Description

I have a failed trade for which I am unable to open a support request. 

The trade failed with this message: 

> The peer's taker fee transaction is missing.
> With out this tx, the trade cannot be completed. No funds have been locked. Your offer is still available to other traders, so you have not lost the maker fee. You can move this trade to failed trades. 

The next screen says: 

> Open support ticket
> Thre is an issue with a missing or invalid transaction. 
> Please do NOT send the fiat or altcoin payment. 
> Open a support ticket to get assistance from a Mediator. 
> Error message: Validation of Taker Tx returned: [Tx not found]

Clicking Open Support Ticket returns the following error: 

> Cannot invoke "org.bitcoinj.core.Transaction.getLockTime()" because the return value of "bisq.core.trade.Trade.getDelayedPayoutTx()" is null

#### Version

v1.7.5

### Steps to reproduce

1. Trade is in a failed state
2. Click "Move trade to open trades" and click "Yes" to confirm
3. Click Open Trades. 
4. Dialog pops up; click "Open Support Ticket"
5. Error is raised. 

### Expected behaviour

Support request is opened.

### Actual behaviour

Error is raised: 

> Cannot invoke "org.bitcoinj.core.Transaction.getLockTime()" because the return value of "bisq.core.trade.Trade.getDelayedPayoutTx()" is null

### Screenshots

![image](https://user-images.githubusercontent.com/234/139870083-d5ceeaf5-f0e0-4904-a0b4-1e51c53c468b.png)

![image](https://user-images.githubusercontent.com/234/139868989-a0268133-69ea-40bb-b174-dc6804a46832.png)

#### Device or machine

MacOs 11.6 (20G165) 
MacBook Pro (16-inch, 2019) 2.3 GHz 8-Core Intel Core i9

**Comment by ryenski** [comment]
Dialog displayed when moving trade to Failed: 

![image](https://user-images.githubusercontent.com/234/139870718-9fa2d18d-d016-49cd-af56-6643a79cd3db.png)

**Comment by ryenski** [comment]
Dialog displayed when clicking the Attention icon in Open Trades: 
![image](https://user-images.githubusercontent.com/234/139870952-ae623100-f75a-4f4e-8f1a-6d9039ac7409.png)

**Comment by ryenski** [comment]
This dialog keeps popping up persistently while I'm trying to navigate around Bisq: 

![image](https://user-images.githubusercontent.com/234/139871504-79203278-6aeb-4b35-b0a8-ce8867c10e50.png)

**Comment by ghost** [comment]
- Looks like a failed trade where no taker and deposit transactions were created.
- You can check if you have locked up funds by looking up the deposit tx address shown in the above screenshot.  If there is no deposit transaction, your funds are not locked.  The false error is known and being worked on.
- The problem of the persistent warning popup is addressed by [PR 5771](https://github.com/bisq-network/bisq/pull/5771) due for the next release.
- A fix for the problem of opening a support ticket will be made shortly.

Thanks for reporting - Sorry for the inconvenience.

**Comment by ryenski** [comment]
Thank you. I'm not 100% sure I typed it in correctly, but [bc1qy0q7gxxvm4wpgeym3sypj3728hyctz4a7rm0c3](https://mempool.space/address/bc1qy0q7gxxvm4wpgeym3sypj3728hyctz4a7rm0c3) does not appear to be used. 

However I still appear to have 0.0162 BTC locked up in that transaction, which I can't close: 

![image](https://user-images.githubusercontent.com/234/139880991-82913bc1-6c1f-45fc-997f-971b8732448c.png)

**Comment by SatoshiGardener** [comment]
The weird thing is that neither the Maker fee nor the Deposit transaction ID appear to be related to this transaction: 

Maker fee transaction ID: https://mempool.space/tx/736d62807bdb904a29bcedeaa208406298c1dee2b716c83ba79c2b540c745467

Deposit transaction id: https://mempool.space/tx/1c7a9cb978a4c9346110ff705e87e594e94e2e44fe668b9a1df8da23bf463ec1

**Comment by ryenski** [comment]
The funds are listed under Locked Funds as well: 

![image](https://user-images.githubusercontent.com/234/139884148-5f8bb1d0-a835-46f8-95de-1fa8d2700865.png)

https://mempool.space/address/bc1qfuvtcv92evpm5p8um2u75kp2s6cyy8ddhv7xld6q38xg2m97wjgqux5px6

**Comment by ryenski** [comment]
> * Looks like a failed trade where no taker and deposit transactions were created.

You're right that the taker transaction was not created, but I believe the deposit transaction was: https://mempool.space/tx/1c7a9cb978a4c9346110ff705e87e594e94e2e44fe668b9a1df8da23bf463ec1

**Comment by ghost** [comment]
Thanks for the context, your observations are correct and looks like your funds are locked.  Its a very odd situation - please could you DM me your logs on keybase for further investigation & support.
